# https://github.com/rfc1036/whois/blob/next/tld_serv_list
tld_serv_list = [
('.br.com', 'whois.centralnic.net'),
('.cn.com', 'whois.centralnic.net'),
('.de.com', 'whois.centralnic.net'),
('.eu.com', 'whois.centralnic.net'),
('.gb.com', 'whois.centralnic.net'),
('.gb.net', 'whois.centralnic.net'),
('.gr.com', 'whois.centralnic.net'),
('.hu.com', 'whois.centralnic.net'),
('.in.net', 'whois.centralnic.net'),
('.no.com', 'whois.centralnic.net'),
('.qc.com', 'whois.centralnic.net'),
('.ru.com', 'whois.centralnic.net'),
('.sa.com', 'whois.centralnic.net'),
('.se.com', 'whois.centralnic.net'),
('.se.net', 'whois.centralnic.net'),
('.uk.com', 'whois.centralnic.net'),
('.uk.net', 'whois.centralnic.net'),
('.us.com', 'whois.centralnic.net'),
('.uy.com', 'whois.centralnic.net'),
('.za.com', 'whois.centralnic.net'),
('.jpn.com', 'whois.centralnic.net'),
('.web.com', 'whois.centralnic.net'),

('.com', 'whois.verisign-grs.com'),

('.za.net', 'whois.za.net'),
('.net', 'whois.verisign-grs.com'),

('.eu.org', 'whois.eu.org'),
('.za.org', 'whois.za.org'),
('.org', 'whois.pir.org'),

('.edu', 'whois.educause.edu'),
('.gov', 'whois.dotgov.gov'),
('.int', 'whois.iana.org'),

('.e164.arpa', 'whois.ripe.net'),
('.in-addr.arpa', 'ARPA'),
('.ip6.arpa', 'IP6'),
('.arpa', 'whois.iana.org'),

('.aero', 'whois.aero'),
('.asia', 'whois.nic.asia'),
('.biz', 'whois.nic.biz'),
('.cat', 'whois.nic.cat'),
('.coop', 'whois.nic.coop'),
('.info', 'whois.afilias.net'),
('.jobs', 'whois.nic.jobs'),
('.mobi', 'whois.afilias.net'),
('.museum', 'whois.nic.museum'),
('.name', 'whois.nic.name'),
('.post', 'whois.dotpostregistry.net'),
('.pro', 'whois.afilias.net'),
('.tel', 'whois.nic.tel'),
('.travel', 'whois.nic.travel'),
('.xxx', 'whois.registrar.adult'),

('.ac', 'whois.nic.ac'),
('.ae', 'whois.aeda.net.ae'),
('.af', 'whois.nic.af'),
('.ag', 'whois.nic.ag'),
('.ai', 'whois.nic.ai'),
('.am', 'whois.amnic.net'),
('.ar', 'whois.nic.ar'),
('.as', 'whois.nic.as'),
('.priv.at', 'whois.nic.priv.at'),
('.at', 'whois.nic.at'),
('.au', 'whois.auda.org.au'),
('.aw', 'whois.nic.aw'),
('.ax', 'whois.ax'),
('.be', 'whois.dns.be'),
('.bg', 'whois.register.bg'),
('.bh', 'whois.nic.bh'),
('.bi', 'whois1.nic.bi'),
('.bj', 'whois.nic.bj'),
('.bm', 'whois.afilias-srs.net'),
('.bn', 'whois.bnnic.bn'),
('.bo', 'whois.nic.bo'),
('.br', 'whois.registro.br'),
('.by', 'whois.cctld.by'),
('.bw', 'whois.nic.net.bw'),
('.co.ca', 'whois.co.ca'),
('.ca', 'whois.cira.ca'),
('.cc', 'ccwhois.verisign-grs.com'),
('.ch', 'whois.nic.ch'),
('.ci', 'whois.nic.ci'),
('.cl', 'whois.nic.cl'),
('.cm', 'whois.netcom.cm'),
('.edu.cn', 'whois.edu.cn'),
('.cn', 'whois.cnnic.cn'),
('.uk.co', 'whois.uk.co'),
('.co', 'whois.nic.co'),
('.cr', 'whois.nic.cr'),
('.cx', 'whois.nic.cx'),
('.cz', 'whois.nic.cz'),
('.de', 'whois.denic.de'),
('.dk', 'whois.dk-hostmaster.dk'),
('.dm', 'whois.nic.dm'),
('.do', 'whois.nic.do'),
('.dz', 'whois.nic.dz'),
('.ec', 'whois.nic.ec'),
('.ee', 'whois.tld.ee'),
('.eu', 'whois.eu'),
('.fi', 'whois.fi'),
('.fj', 'whois.usp.ac.fj'),
('.fm', 'whois.nic.fm'),
('.fo', 'whois.nic.fo'),
('.fr', 'whois.nic.fr'),
('.gd', 'whois.nic.gd'),
('.ge', 'whois.nic.ge'),
('.gf', 'whois.mediaserv.net'),
('.gg', 'whois.gg'),
('.gh', 'whois.nic.gh'),
('.gi', 'whois2.afilias-grs.net'),
('.gl', 'whois.nic.gl'),
('.gp', 'whois.nic.gp'),
('.gq', 'whois.dominio.gq'),
('.gs', 'whois.nic.gs'),
('.gy', 'whois.registry.gy'),
('.hk', 'whois.hkirc.hk'),
('.hm', 'whois.registry.hm'),
('.hn', 'whois.nic.hn'),
('.hr', 'whois.dns.hr'),
('.ht', 'whois.nic.ht'),
('.hu', 'whois.nic.hu'),
('.id', 'whois.id'),
('.ie', 'whois.weare.ie'),
('.il', 'whois.isoc.org.il'),
('.im', 'whois.nic.im'),
('.in', 'whois.registry.in'),
('.io', 'whois.nic.io'),
('.iq', 'whois.cmc.iq'),
('.ir', 'whois.nic.ir'),
('.is', 'whois.isnic.is'),
('.it', 'whois.nic.it'),
('.je', 'whois.je'),
('.jp', 'whois.jprs.jp'),
('.ke', 'whois.kenic.or.ke'),
('.kg', 'whois.kg'),
('.ki', 'whois.nic.ki'),
('.kn', 'whois.nic.kn'),
('.kr', 'whois.kr'),
('.kw', 'whois.nic.kw'),
('.ky', 'whois.kyregistry.ky'),
('.kz', 'whois.nic.kz'),
('.la', 'whois.nic.la'),
('.lb', 'whois.lbdr.org.lb'),
('.lc', 'whois2.afilias-grs.net'),
('.li', 'whois.nic.li'),
('.lk', 'whois.nic.lk'),
('.ls', 'whois.nic.ls'),
('.lt', 'whois.domreg.lt'),
('.lu', 'whois.dns.lu'),
('.lv', 'whois.nic.lv'),
('.ly', 'whois.nic.ly'),
('.ma', 'whois.registre.ma'),
('.md', 'whois.nic.md'),
('.me', 'whois.nic.me'),
('.mg', 'whois.nic.mg'),
('.mk', 'whois.marnet.mk'),
('.ml', 'whois.dot.ml'),
('.mm', 'whois.registry.gov.mm'),
('.mn', 'whois.nic.mn'),
('.mq', 'whois.mediaserv.net'),
('.mr', 'whois.nic.mr'),
('.ms', 'whois.nic.ms'),
('.mu', 'whois.nic.mu'),
('.mw', 'whois.nic.mw'),
('.mx', 'whois.mx'),
('.my', 'whois.mynic.my'),
('.mz', 'whois.nic.mz'),
('.na', 'whois.na-nic.com.na'),
('.nc', 'whois.nc'),
('.nf', 'whois.nic.nf'),
('.ng', 'whois.nic.net.ng'),
('.nl', 'whois.domain-registry.nl'),
('.no', 'whois.norid.no'),
('.nu', 'whois.iis.nu'),
('.nz', 'whois.srs.net.nz'),
('.om', 'whois.registry.om'),
('.pe', 'kero.yachay.pe'),
('.pf', 'whois.registry.pf'),
('.co.pl', 'whois.co.pl'),
('.pl', 'whois.dns.pl'),
('.pm', 'whois.nic.pm'),
('.pr', 'whois.afilias-srs.net'),
('.ps', 'whois.pnina.ps'),
('.pt', 'whois.dns.pt'),
('.pw', 'whois.nic.pw'),
('.qa', 'whois.registry.qa'),
('.re', 'whois.nic.re'),
('.ro', 'whois.rotld.ro'),
('.rs', 'whois.rnids.rs'),
('.ac.ru', 'whois.free.net'),
('.edu.ru', 'whois.informika.ru'),
('.com.ru', 'whois.flexireg.net'),
('.msk.ru', 'whois.flexireg.net'),
('.net.ru', 'whois.nic.net.ru'),
('.nov.ru', 'whois.flexireg.net'),
('.org.ru', 'whois.nic.net.ru'),
('.pp.ru', 'whois.nic.net.ru'),
('.spb.ru', 'whois.flexireg.net'),
('.ru', 'whois.tcinet.ru'),
('.rw', 'whois.ricta.org.rw'),
('.sa', 'whois.nic.net.sa'),
('.sb', 'whois.nic.net.sb'),
('.sc', 'whois2.afilias-grs.net'),
('.se', 'whois.iis.se'),
('.sg', 'whois.sgnic.sg'),
('.sh', 'whois.nic.sh'),
('.si', 'whois.register.si'),
('.sk', 'whois.sk-nic.sk'),
('.sl', 'whois.nic.sl'),
('.sm', 'whois.nic.sm'),
('.sn', 'whois.nic.sn'),
('.so', 'whois.nic.so'),
('.ss', 'whois.nic.ss'),
('.st', 'whois.nic.st'),
('.msk.su', 'whois.flexireg.net'),
('.nov.su', 'whois.flexireg.net'),
('.spb.su', 'whois.flexireg.net'),
('.su', 'whois.tcinet.ru'),
('.sx', 'whois.sx'),
('.sy', 'whois.tld.sy'),
('.tc', 'whois.nic.tc'),
('.td', 'whois.nic.td'),
('.tf', 'whois.nic.tf'),
('.tg', 'whois.nic.tg'),
('.th', 'whois.thnic.co.th'),
('.tk', 'whois.dot.tk'),
('.tl', 'whois.nic.tl'),
('.tm', 'whois.nic.tm'),
('.tn', 'whois.ati.tn'),
('.to', 'whois.tonic.to'),
('.tr', 'whois.nic.tr'),
('.tv', 'tvwhois.verisign-grs.com'),
('.tw', 'whois.twnic.net.tw'),
('.tz', 'whois.tznic.or.tz'),
('.biz.ua', 'whois.biz.ua'),
('.co.ua', 'whois.co.ua'),
('.pp.ua', 'whois.pp.ua'),
('.ua', 'whois.ua'),
('.ug', 'whois.co.ug'),
('.ac.uk', 'whois.ja.net'),
('.gov.uk', 'whois.ja.net'),
('.uk', 'whois.nic.uk'),
('.fed.us', 'whois.nic.gov'),
('.us', 'whois.nic.us'),
('.uy', 'whois.nic.org.uy'),
('.uz', 'whois.cctld.uz'),
('.vc', 'whois2.afilias-grs.net'),
('.ve', 'whois.nic.ve'),
('.vg', 'whois.nic.vg'),
('.vu', 'whois.dnrs.neustar'),
('.wf', 'whois.nic.wf'),
('.ws', 'whois.website.ws'),
('.yt', 'whois.nic.yt'),
('.ac.za', 'whois.ac.za'),
('.alt.za', 'whois.alt.za'),
('.co.za', 'whois.registry.net.za'),
('.gov.za', 'whois.gov.za'),
('.net.za', 'net-whois.registry.net.za'),
('.org.za', 'org-whois.registry.net.za'),
('.web.za', 'web-whois.registry.net.za'),
('.zm', 'whois.zicta.zm'),

# AW means that I had to guess the whois server name, but I was not able
# to find any registered subdomains to verify it.
('.xn--2scrj9c', 'whois.registry.in'),
('.xn--3e0b707e', 'whois.kr'),
('.xn--3hcrj9c', 'whois.registry.in'),
('.xn--45br5cyl', 'whois.registry.in'),
('.xn--45brj9c', 'whois.registry.in'),
('.xn--4dbrk0ce', 'whois.isoc.org.il'),
('.xn--80ao21a', 'whois.nic.kz'),
('.xn--90a3ac', 'whois.rnids.rs'),
('.xn--90ae', 'whois.imena.bg'),
('.xn--90ais', 'whois.cctld.by'),
('.xn--clchc0ea0b2g2a9gcd', 'whois.sgnic.sg'),
('.xn--d1alf', 'whois.marnet.mk'),
('.xn--e1a4c', 'whois.eu'),
('.xn--fiqs8s', 'cwhois.cnnic.cn'),
('.xn--fiqz9s', 'cwhois.cnnic.cn'),
('.xn--fpcrj9c3d', 'whois.registry.in'),
('.xn--fzc2c9e2c', 'whois.nic.lk'),
('.xn--gecrj9c', 'whois.registry.in'),
('.xn--h2breg3eve', 'whois.registry.in'),
('.xn--h2brj9c8c', 'whois.registry.in'),
('.xn--h2brj9c', 'whois.registry.in'),
('.xn--j1amh', 'whois.dotukr.com'),
('.xn--j6w193g', 'whois.hkirc.hk'),
('.xn--kprw13d', 'whois.twnic.net.tw'),
('.xn--kpry57d', 'whois.twnic.net.tw'),
('.xn--lgbbat1ad8j', 'whois.nic.dz'),
('.xn--mgb9awbf', 'whois.registry.om'),
('.xn--mgba3a4f16a', 'whois.nic.ir'),
('.xn--mgbaam7a8h', 'whois.aeda.net.ae'),
('.xn--mgbah1a3hjkrd', 'whois.nic.mr'),
('.xn--mgbbh1a71e', 'whois.registry.in'),
('.xn--mgbbh1a', 'whois.registry.in'),
('.xn--mgberp4a5d4ar', 'whois.nic.net.sa'),
('.xn--mgbgu82a', 'whois.registry.in'),
('.xn--mgbtx2b', 'whois.cmc.iq'),
('.xn--mgbx4cd0ab', 'whois.mynic.my'),
('.xn--node', 'whois.itdc.ge'),
('.xn--o3cw4h', 'whois.thnic.co.th'),
('.xn--ogbpf8fl', 'whois.tld.sy'),
('.xn--p1ai', 'whois.tcinet.ru'),
('.xn--pgbs0dh', 'whois.ati.tn'),
('.xn--q7ce6a', 'whois.nic.la'),
('.xn--qxa6a', 'whois.eu'),
('.xn--rvc1e0am3e', 'whois.registry.in'),
('.xn--s9brj9c', 'whois.registry.in'),
('.xn--wgbh1c', 'whois.dotmasr.eg'),
('.xn--wgbl6a', 'whois.registry.qa'),
('.xn--xkc2al3hye2a', 'whois.nic.lk'),
('.xn--xkc2dl3a5ee0h', 'whois.registry.in'),
('.xn--y9a3aq', 'whois.amnic.net'),
('.xn--yfro4i67o', 'whois.sgnic.sg'),
('.xn--ygbi2ammx', 'whois.pnina.ps'),
]

# https://github.com/rfc1036/whois/blob/next/new_gtlds_list
new_gtlds_list = [
'aaa',
'aarp',
'abarth',
'abb',
'abbott',
'abbvie',
'abc',
'able',
'abogado',
'abudhabi',
'academy',
'accenture',
'accountant',
'accountants',
'aco',
'actor',
'adac',
'ads',
'adult',
'aeg',
'aetna',
'afamilycompany',
'afl',
'africa',
'agakhan',
'agency',
'aig',
'airbus',
'airforce',
'airtel',
'akdn',
'alfaromeo',
'alibaba',
'alipay',
'allfinanz',
'allstate',
'ally',
'alsace',
'alstom',
'amazon',
'americanexpress',
'americanfamily',
'amex',
'amfam',
'amica',
'amsterdam',
'analytics',
'android',
'anquan',
'anz',
'aol',
'apartments',
'app',
'apple',
'aquarelle',
'arab',
'aramco',
'archi',
'army',
'art',
'arte',
'asda',
'associates',
'athleta',
'attorney',
'auction',
'audi',
'audible',
'audio',
'auspost',
'author',
'auto',
'autos',
'avianca',
'aws',
'axa',
'azure',
'baby',
'baidu',
'banamex',
'bananarepublic',
'band',
'bank',
'bar',
'barcelona',
'barclaycard',
'barclays',
'barefoot',
'bargains',
'baseball',
'basketball',
'bauhaus',
'bayern',
'bbc',
'bbt',
'bbva',
'bcg',
'bcn',
'beats',
'beauty',
'beer',
'bentley',
'berlin',
'best',
'bestbuy',
'bet',
'bharti',
'bible',
'bid',
'bike',
'bing',
'bingo',
'bio',
'black',
'blackfriday',
'blockbuster',
'blog',
'bloomberg',
'blue',
'bms',
'bmw',
'bnpparibas',
'boats',
'boehringer',
'bofa',
'bom',
'bond',
'boo',
'book',
'booking',
'bosch',
'bostik',
'boston',
'bot',
'boutique',
'box',
'bradesco',
'bridgestone',
'broadway',
'broker',
'brother',
'brussels',
'budapest',
'bugatti',
'build',
'builders',
'business',
'buy',
'buzz',
'bzh',
'cab',
'cafe',
'cal',
'call',
'calvinklein',
'cam',
'camera',
'camp',
'cancerresearch',
'canon',
'capetown',
'capital',
'capitalone',
'car',
'caravan',
'cards',
'care',
'career',
'careers',
'cars',
'casa',
'case',
'cash',
'casino',
'catering',
'catholic',
'cba',
'cbn',
'cbre',
'cbs',
'center',
'ceo',
'cern',
'cfa',
'cfd',
'chanel',
'channel',
'charity',
'chase',
'chat',
'cheap',
'chintai',
'christmas',
'chrome',
'church',
'cipriani',
'circle',
'cisco',
'citadel',
'citi',
'citic',
'city',
'cityeats',
'claims',
'cleaning',
'click',
'clinic',
'clinique',
'clothing',
'cloud',
'club',
'clubmed',
'coach',
'codes',
'coffee',
'college',
'cologne',
'comcast',
'commbank',
'community',
'company',
'compare',
'computer',
'comsec',
'condos',
'construction',
'consulting',
'contact',
'contractors',
'cooking',
'cookingchannel',
'cool',
'corsica',
'country',
'coupon',
'coupons',
'courses',
'cpa',
'credit',
'creditcard',
'creditunion',
'cricket',
'crown',
'crs',
'cruise',
'cruises',
'csc',
'cuisinella',
'cymru',
'cyou',
'dabur',
'dad',
'dance',
'data',
'date',
'dating',
'datsun',
'day',
'dclk',
'dds',
'deal',
'dealer',
'deals',
'degree',
'delivery',
'dell',
'deloitte',
'delta',
'democrat',
'dental',
'dentist',
'desi',
'design',
'dev',
'dhl',
'diamonds',
'diet',
'digital',
'direct',
'directory',
'discount',
'discover',
'dish',
'diy',
'dnp',
'docs',
'doctor',
'dog',
'domains',
'dot',
'download',
'drive',
'dtv',
'dubai',
'duck',
'dunlop',
'dupont',
'durban',
'dvag',
'dvr',
'earth',
'eat',
'eco',
'edeka',
'education',
'email',
'emerck',
'energy',
'engineer',
'engineering',
'enterprises',
'epson',
'equipment',
'ericsson',
'erni',
'esq',
'estate',
'etisalat',
'eurovision',
'eus',
'events',
'exchange',
'expert',
'exposed',
'express',
'extraspace',
'fage',
'fail',
'fairwinds',
'faith',
'family',
'fan',
'fans',
'farm',
'farmers',
'fashion',
'fast',
'fedex',
'feedback',
'ferrari',
'ferrero',
'fiat',
'fidelity',
'fido',
'film',
'final',
'finance',
'financial',
'fire',
'firestone',
'firmdale',
'fish',
'fishing',
'fit',
'fitness',
'flickr',
'flights',
'flir',
'florist',
'flowers',
'fly',
'foo',
'food',
'foodnetwork',
'football',
'ford',
'forex',
'forsale',
'forum',
'foundation',
'fox',
'free',
'fresenius',
'frl',
'frogans',
'frontdoor',
'frontier',
'ftr',
'fujitsu',
'fun',
'fund',
'furniture',
'futbol',
'fyi',
'gal',
'gallery',
'gallo',
'gallup',
'game',
'games',
'gap',
'garden',
'gay',
'gbiz',
'gdn',
'gea',
'gent',
'genting',
'george',
'ggee',
'gift',
'gifts',
'gives',
'giving',
'glade',
'glass',
'gle',
'global',
'globo',
'gmail',
'gmbh',
'gmo',
'gmx',
'godaddy',
'gold',
'goldpoint',
'golf',
'goo',
'goodyear',
'goog',
'google',
'gop',
'got',
'grainger',
'graphics',
'gratis',
'green',
'gripe',
'grocery',
'group',
'guardian',
'gucci',
'guge',
'guide',
'guitars',
'guru',
'hair',
'hamburg',
'hangout',
'haus',
'hbo',
'hdfc',
'hdfcbank',
'health',
'healthcare',
'help',
'helsinki',
'here',
'hermes',
'hgtv',
'hiphop',
'hisamitsu',
'hitachi',
'hiv',
'hkt',
'hockey',
'holdings',
'holiday',
'homedepot',
'homegoods',
'homes',
'homesense',
'honda',
'horse',
'hospital',
'host',
'hosting',
'hot',
'hoteles',
'hotels',
'hotmail',
'house',
'how',
'hsbc',
'hughes',
'hyatt',
'hyundai',
'ibm',
'icbc',
'ice',
'icu',
'ieee',
'ifm',
'ikano',
'imamat',
'imdb',
'immo',
'immobilien',
'inc',
'industries',
'infiniti',
'ing',
'ink',
'institute',
'insurance',
'insure',
'international',
'intuit',
'investments',
'ipiranga',
'irish',
'ismaili',
'ist',
'istanbul',
'itau',
'itv',
'jaguar',
'java',
'jcb',
'jeep',
'jetzt',
'jewelry',
'jio',
'jll',
'jmp',
'jnj',
'joburg',
'jot',
'joy',
'jpmorgan',
'jprs',
'juegos',
'juniper',
'kaufen',
'kddi',
'kerryhotels',
'kerrylogistics',
'kerryproperties',
'kfh',
'kia',
'kim',
'kinder',
'kindle',
'kitchen',
'kiwi',
'koeln',
'komatsu',
'kosher',
'kpmg',
'kpn',
'krd',
'kred',
'kuokgroup',
'kyoto',
'lacaixa',
'lamborghini',
'lamer',
'lancaster',
'lancia',
'land',
'landrover',
'lanxess',
'lasalle',
'lat',
'latino',
'latrobe',
'law',
'lawyer',
'lds',
'lease',
'leclerc',
'lefrak',
'legal',
'lego',
'lexus',
'lgbt',
'lidl',
'life',
'lifeinsurance',
'lifestyle',
'lighting',
'like',
'lilly',
'limited',
'limo',
'lincoln',
'linde',
'link',
'lipsy',
'live',
'living',
'lixil',
'llc',
'llp',
'loan',
'loans',
'locker',
'locus',
'loft',
'lol',
'london',
'lotte',
'lotto',
'love',
'lpl',
'lplfinancial',
'ltd',
'ltda',
'lundbeck',
'luxe',
'luxury',
'macys',
'madrid',
'maif',
'maison',
'makeup',
'man',
'management',
'mango',
'map',
'market',
'marketing',
'markets',
'marriott',
'marshalls',
'maserati',
'mattel',
'mba',
'mckinsey',
'med',
'media',
'meet',
'melbourne',
'meme',
'memorial',
'men',
'menu',
'merckmsd',
'miami',
'microsoft',
'mini',
'mint',
'mit',
'mitsubishi',
'mlb',
'mls',
'mma',
'mobile',
'moda',
'moe',
'moi',
'mom',
'monash',
'money',
'monster',
'mormon',
'mortgage',
'moscow',
'moto',
'motorcycles',
'mov',
'movie',
'msd',
'mtn',
'mtr',
'mutual',
'nab',
'nagoya',
'natura',
'navy',
'nba',
'nec',
'netbank',
'netflix',
'network',
'neustar',
'new',
'news',
'next',
'nextdirect',
'nexus',
'nfl',
'ngo',
'nhk',
'nico',
'nike',
'nikon',
'ninja',
'nissan',
'nissay',
'nokia',
'northwesternmutual',
'norton',
'now',
'nowruz',
'nowtv',
'nra',
'nrw',
'ntt',
'nyc',
'obi',
'observer',
'off',
'office',
'okinawa',
'olayan',
'olayangroup',
'oldnavy',
'ollo',
'omega',
'one',
'ong',
'onl',
'online',
'ooo',
'open',
'oracle',
'orange',
'organic',
'origins',
'osaka',
'otsuka',
'ott',
'ovh',
'page',
'panasonic',
'paris',
'pars',
'partners',
'parts',
'party',
'passagens',
'pay',
'pccw',
'pet',
'pfizer',
'pharmacy',
'phd',
'philips',
'phone',
'photo',
'photography',
'photos',
'physio',
'pics',
'pictet',
'pictures',
'pid',
'pin',
'ping',
'pink',
'pioneer',
'pizza',
'place',
'play',
'playstation',
'plumbing',
'plus',
'pnc',
'pohl',
'poker',
'politie',
'porn',
'pramerica',
'praxi',
'press',
'prime',
'prod',
'productions',
'prof',
'progressive',
'promo',
'properties',
'property',
'protection',
'pru',
'prudential',
'pub',
'pwc',
'qpon',
'quebec',
'quest',
'qvc',
'racing',
'radio',
'raid',
'read',
'realestate',
'realtor',
'realty',
'recipes',
'red',
'redstone',
'redumbrella',
'rehab',
'reise',
'reisen',
'reit',
'reliance',
'ren',
'rent',
'rentals',
'repair',
'report',
'republican',
'rest',
'restaurant',
'review',
'reviews',
'rexroth',
'rich',
'richardli',
'ricoh',
'ril',
'rio',
'rip',
'rmit',
'rocher',
'rocks',
'rodeo',
'rogers',
'room',
'rsvp',
'rugby',
'ruhr',
'run',
'rwe',
'ryukyu',
'saarland',
'safe',
'safety',
'sakura',
'sale',
'salon',
'samsclub',
'samsung',
'sandvik',
'sandvikcoromant',
'sanofi',
'sap',
'sarl',
'sas',
'save',
'saxo',
'sbi',
'sbs',
'sca',
'scb',
'schaeffler',
'schmidt',
'scholarships',
'school',
'schule',
'schwarz',
'science',
'scjohnson',
'scot',
'search',
'seat',
'secure',
'security',
'seek',
'select',
'sener',
'services',
'ses',
'seven',
'sew',
'sex',
'sexy',
'sfr',
'shangrila',
'sharp',
'shaw',
'shell',
'shia',
'shiksha',
'shoes',
'shop',
'shopping',
'shouji',
'show',
'showtime',
'silk',
'sina',
'singles',
'site',
'ski',
'skin',
'sky',
'skype',
'sling',
'smart',
'smile',
'sncf',
'soccer',
'social',
'softbank',
'software',
'sohu',
'solar',
'solutions',
'song',
'sony',
'soy',
'spa',
'space',
'sport',
'spot',
'srl',
'stada',
'staples',
'star',
'statebank',
'statefarm',
'stc',
'stcgroup',
'stockholm',
'storage',
'store',
'stream',
'studio',
'study',
'style',
'sucks',
'supplies',
'supply',
'support',
'surf',
'surgery',
'suzuki',
'swatch',
'swiftcover',
'swiss',
'sydney',
'systems',
'tab',
'taipei',
'talk',
'taobao',
'target',
'tatamotors',
'tatar',
'tattoo',
'tax',
'taxi',
'tci',
'tdk',
'team',
'tech',
'technology',
'temasek',
'tennis',
'teva',
'thd',
'theater',
'theatre',
'tiaa',
'tickets',
'tienda',
'tiffany',
'tips',
'tires',
'tirol',
'tjmaxx',
'tjx',
'tkmaxx',
'tmall',
'today',
'tokyo',
'tools',
'top',
'toray',
'toshiba',
'total',
'tours',
'town',
'toyota',
'toys',
'trade',
'trading',
'training',
'travelchannel',
'travelers',
'travelersinsurance',
'trust',
'trv',
'tube',
'tui',
'tunes',
'tushu',
'tvs',
'ubank',
'ubs',
'unicom',
'university',
'uno',
'uol',
'ups',
'vacations',
'vana',
'vanguard',
'vegas',
'ventures',
'verisign',
'versicherung',
'vet',
'viajes',
'video',
'vig',
'viking',
'villas',
'vin',
'vip',
'virgin',
'visa',
'vision',
'viva',
'vivo',
'vlaanderen',
'vodka',
'volkswagen',
'volvo',
'vote',
'voting',
'voto',
'voyage',
'vuelos',
'wales',
'walmart',
'walter',
'wang',
'wanggou',
'watch',
'watches',
'weather',
'weatherchannel',
'webcam',
'weber',
'website',
'wed',
'wedding',
'weibo',
'weir',
'whoswho',
'wien',
'wiki',
'williamhill',
'win',
'windows',
'wine',
'winners',
'wme',
'wolterskluwer',
'woodside',
'work',
'works',
'world',
'wow',
'wtc',
'wtf',
'xbox',
'xerox',
'xfinity',
'xihuan',
'xin',
'xn--11b4c3d',
'xn--1ck2e1b',
'xn--1qqw23a',
'xn--30rr7y',
'xn--3bst00m',
'xn--3ds443g',
'xn--3oq18vl8pn36a',
'xn--3pxu8k',
'xn--42c2d9a',
'xn--45q11c',
'xn--4gbrim',
'xn--55qw42g',
'xn--55qx5d',
'xn--5su34j936bgsg',
'xn--5tzm5g',
'xn--6frz82g',
'xn--6qq986b3xl',
'xn--80adxhks',
'xn--80aqecdr1a',
'xn--8y0a063a',
'xn--9dbq2a',
'xn--9et52u',
'xn--9krt00a',
'xn--b4w605ferd',
'xn--bck1b9a5dre4c',
'xn--c1avg',
'xn--c2br7g',
'xn--cck2b3b',
'xn--cckwcxetd',
'xn--cg4bki',
'xn--czr694b',
'xn--czrs0t',
'xn--czru2d',
'xn--d1acj3b',
'xn--eckvdtc9d',
'xn--efvy88h',
'xn--fct429k',
'xn--fhbei',
'xn--fiq228c5hs',
'xn--fiq64b',
'xn--fjq720a',
'xn--flw351e',
'xn--fzys8d69uvgm',
'xn--g2xx48c',
'xn--gckr3f0f',
'xn--gk3at1e',
'xn--hxt814e',
'xn--i1b6b1a6a2e',
'xn--imr513n',
'xn--io0a7i',
'xn--j1aef',
'xn--jlq480n2rg',
'xn--jlq61u9w7b',
'xn--jvr189m',
'xn--kcrx77d1x4a',
'xn--kput3i',
'xn--mgba3a3ejt',
'xn--mgba7c0bbn0a',
'xn--mgbaakc7dvf',
'xn--mgbab2bd',
'xn--mgbca7dzdo',
'xn--mgbi4ecexp',
'xn--mgbt3dhd',
'xn--mk1bu44c',
'xn--mxtq1m',
'xn--ngbe9e0a',
'xn--ngbrx',
'xn--nqv7f',
'xn--nqv7fs00ema',
'xn--nyqy26a',
'xn--otu796d',
'xn--p1acf',
'xn--pssy2u',
'xn--q9jyb4c',
'xn--qcka1pmc',
'xn--rhqv96g',
'xn--rovu88b',
'xn--ses554g',
'xn--t60b56a',
'xn--tckwe',
'xn--tiq49xqyj',
'xn--vermgensberater-ctb',
'xn--vermgensberatung-pwb',
'xn--vhquv',
'xn--vuq861b',
'xn--w4r85el8fhu5dnra',
'xn--w4rs40l',
'xn--xhq521b',
'xn--zfr164b',
'xyz',
'yachts',
'yahoo',
'yamaxun',
'yandex',
'yodobashi',
'yoga',
'yokohama',
'you',
'youtube',
'yun',
'zappos',
'zara',
'zero',
'zip',
'zone',
'zuerich',
]

def print_rule(suffix, server):
    print('''    {"%s", "%s"},''' % (suffix, server))


if __name__ == '__main__':
    a = []
    for suffix, server in tld_serv_list:
        a.append((suffix, server))
    for suffix in new_gtlds_list:
        a.append(('.' + suffix, 'whois.nic.' + suffix))
    a = sorted(a, key = lambda s: -len(s[0]))
    for suffix, server in a:
        print_rule(suffix, server)
